name: CI/CD Workflow vulture

on:
  push:
    branches: [ main ] 

jobs:
  deploy: 
    name: DeployToProduction 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: tausif40/morematrimony # Replace with your repo name
          ref: main 
          token: ${{ secrets.TOKEN }} # Use your secret

      - name: Connect to VPS using SSH
        uses: webfactory/ssh-agent@v0.5.4 
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }} 

      - name: Check Existing Directory and Delete
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'if [[ -d /var/www/fontend-morematriony/mmorematrimony ]]; then rm -rf /var/www/fontend-morematrimony/morematrimony; fi' 

      - name: Clone Repository (using PAT)
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'git clone https://tausif40:${{ secrets.TOKEN }}@github.com/tausif40/morematrimony.git /var/www/fontend-morematrimony/morematrimony'

      - name: Install Dependencies
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /var/www/fontend-morematrimony/morematrimony && npm install'

      - name: Build Project
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /var/www/fontend-morematrimony/morematrimony && npm run build'
        
      - name: Copy Build to Nginx Directory
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'rsync -avz --delete /var/www/fontend-morematrimony/morematrimony/build/ /var/www/html/matrimony/'
      - name: Restart Nginx
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart nginx'
        
      - name: Restart Node.js Process
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd /var/www/fontend-morematrimony/morematrimony && PATH=$PATH:/usr/local/bin pm2 restart src/App.js' 

